### ISSUE TITLE
Ошибка при парсинге времени возврата в работу

### ISSUE THREAD

**Issue by catemohi** [catemohi/naumen#1]
![image](https://user-images.githubusercontent.com/78559060/189696523-bcc2dda7-7446-4c65-a912-16c53845be45.png)

**Comment by catemohi** [comment]
>>> client.get_issues(parse_card=True)              
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\.dev\projects\dashboard\api.py", line 114, in get_issues
    issue_card = json.loads(
  File "E:\.dev\projects\dashboard\api.py", line 146, in get_issue_card
    log.debug('Запрос данных с карточки обращения.')
  File "E:\.dev\projects\dashboard\api.py", line 283, in _get_response
    try:
  File "E:\.dev\projects\dashboard\client.py", line 177, in get_report
    collect = parse_naumen_page(page_text, name_report, report.page)
  File "E:\.dev\projects\dashboard\parser\parser.py", line 48, in parse_naumen_page
    parsed_collections = parser(page, name_report)
  File "E:\.dev\projects\dashboard\parser\issue_card.py", line 37, in parse
    issue.return_to_work_time = _get_return_to_work_time(soup)
  File "E:\.dev\projects\dashboard\parser\issue_card.py", line 81, in _get_return_to_work_time
    return_to_work_time = sorted(times)[-1]
IndexError: list index out of range

**Comment by catemohi** [comment]
https://github.com/catemohi/naumen/commit/447607d40f97e0f034f3eb9c81ddb883cc02ae02
